"""Produce a Hub-compatible staging directory from a model source directory.

HuggingFace's remote from_pretrained recursively resolves all imports from the
entry-point file into the module cache. Local from_pretrained does not — only
files directly imported from huggingface.py are fetched, causing a crash when
the model tries to load second-level dependencies. The only correct fix is to
inline all model code into a single file before upload.

**What stage() produces**

stage(source_dir, dest_dir) walks source_dir, inlines all Python model code
reachable from source_dir/huggingface.py into a single dest_dir/huggingface.py,
and copies non-Python files (configs, tokenizer files, etc.) into dest_dir
unchanged. The result is a directory from which AutoModelForCausalLM.from_pretrained
with local_files_only=True succeeds.

**How the inliner works**

Naive line-by-line import detection is defeated by multiline parenthesized
imports, inline comments, docstrings containing the word "import", and
TYPE_CHECKING blocks. The inliner therefore operates through a sentinel
pipeline:

1. TYPE_CHECKING blocks are converted to comments so their imports are inert.
2. Docstrings and comments are extracted and replaced with __COMMENT_N__
   sentinels, preventing their content from being misread as live imports.
3. Top-level import blocks — including parenthesized multiline forms — are
   extracted and replaced with __IMPORT_N__ sentinels. Inline comments are
   promoted above the sentinel.
4. Each import block is standardized into canonical single-line forms. The
   six supported forms are:
       import _module_
       import _module_ as _alias_
       from _module_ import _name_
       from _module_ import _name_ as _alias_
       from ._relative_ import _name_
       from ._relative_ import _name_ as _alias_
   Multi-name, parenthesized, and semicolon-separated imports are all expanded
   into these forms. Star imports raise ValueError.
5. Each __IMPORT_N__ sentinel is resolved: relative imports are replaced with
   the recursively inlined content of the target file; external imports are
   emitted on first encounter and commented out on recurrence.
6. __COMMENT_N__ sentinels are restored, returning docstrings and comments to
   the merged source verbatim.
"""

import importlib.util
import shutil
import re
from pathlib import Path
from typing import Dict, Tuple

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_GENERATED_HEADER = (
    "# This file is auto-generated by stage_for_hub.py from the source repository.\n"
    "# Do not edit it directly — changes will be overwritten on the next release.\n"
)

# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------

def _is_module_in_directory(module_name: str, source_dir: Path) -> bool:
    """Return True if module_name resolves to a file under source_dir.

    Uses Python's import machinery to locate where the module lives on disk,
    then checks whether that location falls under source_dir. A True result
    means the import references a local source file rather than an installed
    external package — the caller should raise, because the merged output would
    reference a file that does not exist in the staging environment.

    Raises ValueError rather than returning a default if the module is missing
    from the environment or has no concrete file origin: either condition means
    staging cannot proceed correctly and should crash immediately.

    Args:
        module_name: Top-level module name, e.g. ``torch`` or ``transformers``.
        source_dir: Directory to check against; the directory containing the
            staged huggingface.py entry point.

    Returns:
        True if the module's origin file is under source_dir, False otherwise.

    Raises:
        ValueError: If the module is not found in the current environment or
            has no concrete file origin (e.g. a namespace package).
    """
    spec = importlib.util.find_spec(module_name)
    if spec is None:
        raise ValueError(
            f"Module '{module_name}' not found in the current environment; "
            f"all model dependencies must be installed in the staging environment."
        )
    if spec.origin is None:
        raise ValueError(
            f"Module '{module_name}' has no concrete file origin (namespace package); "
            f"convert any absolute imports of this module to relative imports."
        )
    return Path(spec.origin).is_relative_to(source_dir)


# ---------------------------------------------------------------------------
# Normalisation
# ---------------------------------------------------------------------------

def comment_out_type_checking(source: str) -> str:
    """
    Walks over the source lines, and identifies any
    cases that are just for type hints. If one is found
    it comments it out. Commenting out continues until exiting
    the indentation level
    :param lines: The lines of the source file to check
    :return: The revised lines
    """
    result = []
    in_block = False
    expected_indent = None
    lines = source.split("\n")
    for line in lines:
        if line.startswith("if") and "TYPE_CHECKING" in line:
            # Start new block.
            in_block = True
            expected_indent = None
        elif in_block:
            # Check indent. Capture if not set, or reset if
            # we are lower than target.
            indent = len(line) - len(line.lstrip())
            if indent == 0 and line.strip():
                in_block = False
            elif indent != 0:
                if expected_indent is None:
                    expected_indent = indent
                elif indent < expected_indent:
                    in_block = False

        # If in block, comment it out.
        if in_block:
            line = "# " + line
        result.append(line)

    return "\n".join(result)

def resolve_comments_to_sentinels(source: str) -> Tuple[str, Dict[str, str]]:
    """
    Resolves source code into a proxy of
    a dictionary of comment sentinels, and
    a string with those sentinels standing in for the
    comments. Multiline docstrings and regular comments
    are captured and encoded this way. Substituting
    the sentinels back in reconstructs the string, and
    removing comments prevents triggering on their content.
    :param source: The source to parse from
    :return:
        - The sentinel-filled source
        - The dictionary of sentinel keys to representations.
    """
    sentinels: Dict[str, str] = {}
    counter = 0
    pattern = re.compile(r'(""".*?"""|\'\'\'.*?\'\'\'|#[^\n]*)', re.DOTALL)

    def replace(match: re.Match) -> str:
        nonlocal counter
        key = f"__COMMENT_{counter}__"
        sentinels[key] = match.group(0)
        counter += 1
        return key

    result = pattern.sub(replace, source)
    return result, sentinels

def resolve_import_blocks_to_sentinels(source: str) -> Tuple[str, Dict[str, str]]:
    """
    Resolves top-level import statements into sentinel representations.
    Multiline parenthesized imports are captured as a single block.
    Comments within import lines are promoted above the sentinel in the
    result, preserving them without polluting the import content.
    :param source: The source to parse from, with comments already sentineled.
    :return:
        - The sentinel-filled source
        - The dictionary of sentinel keys to clean import representations.
    """
    sentinels = {}
    counter = 0
    lines = source.split("\n")
    result = []
    it = iter(lines)  # shared iterator allows inner loop to consume continuations from the same position

    for line in it:
        if line.startswith("import ") or line.startswith("from "):
            block = [line]
            if "(" in line:
                # parenthesized import — consume lines from the shared iterator until
                # the block closes, so the outer loop doesn't see them as separate lines
                for continuation in it:
                    block.append(continuation)
                    if ")" in continuation:
                        break

            # strip comment sentinels from block content, collecting them for promotion above the import
            promoted = []
            clean_lines = []
            for block_line in block:
                comments = re.findall(r'__COMMENT_\d+__', block_line)
                promoted.extend(comments)
                clean = re.sub(r'__COMMENT_\d+__', '', block_line).rstrip()
                if clean:
                    clean_lines.append(clean)

            key = f"__IMPORT_{counter}__"
            sentinels[key] = "\n".join(clean_lines)
            counter += 1
            result.extend(promoted)
            result.append(key)
        else:
            result.append(line)

    return "\n".join(result), sentinels
def standardize_import_blocks(sentinels: Dict[str, str]) -> Dict[str, str]:
    """
    Standardizes import blocks to canonical single-line forms.
    Semicolon-separated, comma-separated, and parenthesized imports
    are all split into individual import statements.
    :param sentinels: The import sentinel dict from resolve_import_blocks_to_sentinels
    :return: The same dict with values replaced by standardized import lines.
    """
    result = {}
    for key, block in sentinels.items():
        lines = []

        # Statements involving ";" are split then handled separately.
        for statement in block.split(";"):
            # Break statement into a reusable prefix and a suffix,
            # with one statement or possibly many.
            # Prefix contains the base such as "from . import"
            # Suffix contains remaining statemetns.
            statement = statement.strip()
            prefix, suffix = statement.split("import")
            prefix = prefix + "import"

            #Standardize multicomma statements to exist on a single
            # line.
            if "(" in suffix and ")" in suffix:
                multiline_section = re.search(r'\((.+?)\)', suffix, re.DOTALL)
                replacement_key = multiline_section.group(0)
                contents = multiline_section.group(1)
                contents = contents.replace("\n", "")
                suffix = suffix.replace(replacement_key, contents)

            # Split on commas, strip whitespace, and make statements.
            #
            # In cases where only one statement is needed, we just
            # reconstructed the same one.
            for operand in suffix.split(","):
                operand = operand.strip()
                if len(operand) == 0:
                    # Skips comment only cases.
                    continue
                if operand == "*":
                    raise ValueError(
                        f"Star imports are not supported by the inliner: '{prefix} *'"
                    )

                statement = prefix + " " + operand
                lines.append(statement)

        result[key] = "\n".join(lines)
    return result

def validate_source(sentinel_string):
    """
    If properly handled, nothing should
    say import anymore
    :param sentinel_string:
    """
    lines = sentinel_string.split("\n")
    for i, line in enumerate(lines):
        if "import" in line:
            msg = f"Unsupported import at line {i}\n"
            msg += f"line was: {line}"
            raise ValueError(msg)

def restore_sentinels(source: str, sentinels: Dict[str, str]) -> str:
    """Substitute sentinel keys back into source, restoring original comments."""
    for key, value in sentinels.items():
        source = source.replace(key, value)
    return source


# ---------------------------------------------------------------------------
# Import resolution
# ---------------------------------------------------------------------------

def _resolve_relative_path(module: str, base_dir: Path, import_name: str) -> Path:
    """Resolve a relative import module string to an absolute .py file path.

    Counts the leading dots to determine how many directories to ascend from
    base_dir, then follows the remaining dotted path. When the module string
    contains only dots and no path (bare-dot form, e.g. ``from . import X``),
    import_name is used to locate the target file.

    Resolution order for each candidate location:
      1. <resolved_dir>/<path>.py
      2. <resolved_dir>/<path>/__init__.py

    Args:
        module: Relative module string, e.g. ``.cache.shram_cache`` or ``..``.
        base_dir: Directory of the importing file.
        import_name: The name being imported; used only for bare-dot forms where
            the module string has no path component after the leading dots.

    Returns:
        Absolute path to the resolved .py file.

    Raises:
        FileNotFoundError: If no matching .py file exists at either candidate.
    """
    dots = 0
    for c in module:
        if c == ".":
            dots += 1
        else:
            break

    remainder = module[dots:]

    current = base_dir
    for _ in range(dots - 1):
        current = current.parent

    if remainder:
        parts = remainder.split(".")
        candidate = current.joinpath(*parts).with_suffix(".py")
        if candidate.is_file():
            return candidate
        candidate = current.joinpath(*parts, "__init__.py")
        if candidate.is_file():
            return candidate
    else:
        # Bare-dot form: from . import X.
        # If X resolves to a file, the caller is importing a module as a
        # namespace object (e.g. model.ShramModel). That pattern breaks after
        # inlining because X no longer exists as a name. Raise explicitly.
        candidate = current / (import_name + ".py")
        if candidate.is_file():
            raise ValueError(
                f"Module-as-namespace import 'from {module} import {import_name}' "
                f"is not supported by the inliner. "
                f"Use 'from .{import_name} import SpecificName' instead."
            )
        candidate = current / import_name / "__init__.py"
        if candidate.is_file():
            raise ValueError(
                f"Module-as-namespace import 'from {module} import {import_name}' "
                f"is not supported by the inliner. "
                f"Use 'from .{import_name} import SpecificName' instead."
            )

    raise FileNotFoundError(
        f"Cannot resolve relative import '{module}' "
        f"(name={import_name!r}) from {base_dir}"
    )


def resolve_key(statement: str, base_dir: Path) -> str:
    """Derive the canonical deduplication key for an import statement.

    Relative imports produce a ``rel:<posix-path>`` key using the resolved
    absolute file path. External imports produce an ``abs:<statement>`` key
    using the import statement text. Both forms are stored in the shared seen
    set by resolve_import.

    Args:
        statement: A canonical single-line import statement.
        base_dir: Directory of the file containing the statement; used to
            resolve relative import paths.

    Returns:
        Canonical string key for use in the seen set.
    """
    parts = statement.split()

    if parts[0] == "from" and parts[1].startswith("."):
        # Relative import. import_name is the symbol after the "import" keyword.
        import_name = parts[3] if len(parts) > 3 else ""
        resolved = _resolve_relative_path(parts[1], base_dir, import_name)
        return f"rel:{resolved.as_posix()}"

    return f"abs:{statement}"


def resolve_import(key: str, seen: set[str], _external: list[str] | None = None, source_dir: Path | None = None) -> str:
    """Resolve an import key to its substitution string.

    On first encounter of a relative import, marks the key as seen and returns
    the inlined file content preceded by a section header identifying the source
    file. On first encounter of an external import, appends the statement to
    _external (if provided) and returns empty string so the statement is emitted
    at the top of the merged file rather than inline. On subsequent encounters
    of either kind, returns empty string — relative imports are already inlined,
    and external imports are already collected.

    When source_dir is provided, absolute imports that resolve to files under
    source_dir raise ValueError immediately — they are local source references
    disguised as external imports and would produce broken merged output.

    Args:
        key: Canonical key from resolve_key.
        seen: Shared set of already-processed keys; mutated by this call.
        _external: Shared list for collecting external import statements;
            populated on first encounter of each abs: key. When None, external
            imports are emitted inline (backward-compatible path).
        source_dir: Source directory of the staged model; passed to
            _is_module_in_directory to detect local absolute imports. When
            None, local import detection is skipped.

    Returns:
        Substitution string for the sentinel.
    """
    if key in seen:
        return ""

    seen.add(key)

    if key.startswith("rel:"):
        header = f"# -----------\n# Inlined from: {Path(key[4:]).name}\n# -----------"
        return header + "\n" + inline_imports(Path(key[4:]), seen, _external, source_dir)

    # External import: collect for top-of-file emission.
    if _external is not None:
        statement = key[4:]
        if source_dir is not None:
            top_level = statement.split()[1].split(".")[0]
            if _is_module_in_directory(top_level, source_dir):
                raise ValueError(
                    f"Absolute import resolves to a local source file and must be "
                    f"converted to a relative import: {statement}"
                )
        _external.append(statement)
        return ""
    return key[4:]


# ---------------------------------------------------------------------------
# Inlining orchestration
# ---------------------------------------------------------------------------

def inline_imports(path: Path, seen: set[str] | None = None, _external: list[str] | None = None, source_dir: Path | None = None) -> str:
    """Inline all imports in a Python file, recursively following relative imports.

    Processes the file through the normalization pipeline, resolves each import
    sentinel, and performs string substitution to produce the merged source.
    Relative imports are replaced with the full recursively inlined content of
    the imported file, preceded by a section header. External imports are
    collected into _external and emitted once at the top of the merged file via
    an __IMPORT_ABS__ sentinel, which is inserted after the module docstring on
    the top-level call and replaced with the collected statements at the end.

    Args:
        path: Absolute path to the Python source file to inline.
        seen: Shared set of already-processed keys. An empty set is created if
            None; callers may pass an existing set to share deduplication state
            across the recursive call chain.
        _external: Shared list for collecting external import statements. Created
            at the top-level call and passed through recursive calls. When None,
            this is the top-level call.
        source_dir: Source directory of the staged model. Captured from
            path.parent at the top-level call and threaded through recursive
            calls so resolve_import can detect local absolute imports.

    Returns:
        Merged Python source with all relative imports inlined.

    Raises:
        ValueError: If unsupported import constructs are found, with the source
            file path included in the message.
    """
    if seen is None:
        seen = set()

    is_top_level = _external is None
    if is_top_level:
        _external = []
        source_dir = path.parent

    source = path.read_text(encoding="utf-8")

    try:
        source = comment_out_type_checking(source)
        source, comment_sentinels = resolve_comments_to_sentinels(source)

        if is_top_level:
            match = re.search(r'__COMMENT_\d+__', source)
            if match:
                source = source[:match.end()] + "\n__IMPORT_ABS__" + source[match.end():]
            else:
                source = "__IMPORT_ABS__\n" + source

        source, import_sentinels = resolve_import_blocks_to_sentinels(source)
        import_sentinels = standardize_import_blocks(import_sentinels)
        validate_source(source)
    except ValueError as e:
        raise ValueError(f"{path}: {e}") from e

    for sentinel, block in import_sentinels.items():
        parts = []
        for line in block.splitlines():
            line = line.strip()
            if not line:
                continue
            key = resolve_key(line, path.parent)
            replacement = resolve_import(key, seen, _external, source_dir)
            if replacement:
                parts.append(replacement)
        source = source.replace(sentinel, "\n".join(parts))

    source = restore_sentinels(source, comment_sentinels)

    if is_top_level:
        source = source.replace("__IMPORT_ABS__", "\n".join(_external))

    return source


# ---------------------------------------------------------------------------
# Staging
# ---------------------------------------------------------------------------

def stage_model(source_dir: Path, dest_dir: Path) -> None:
    """Flatten source_dir into dest_dir as a single merged huggingface.py.

    Inlines all Python code reachable from source_dir/huggingface.py into a
    single dest_dir/huggingface.py. The merged file begins with a generated-file
    header, followed by all external imports collected at the top after the
    module docstring, then the inlined code with section headers marking each
    source file's contribution. Non-Python files are copied unchanged.
    dest_dir must already exist and should be empty.

    Args:
        source_dir: Source model directory (e.g. src/shram/model/).
        dest_dir: Destination staging directory to write the merged file into.
    """
    merged = inline_imports(source_dir / "huggingface.py")
    merged = _GENERATED_HEADER + "\n" + merged
    (dest_dir / "huggingface.py").write_text(merged, encoding="utf-8")
